baseURL: "https://dineshcodes.netlify.app/"
languageCode: en-us
title: Dinesh
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: education
      name: Education
      url: /education
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50


params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "D R Dinesh Kumar"
    subtitle: Hi 👋! I'm Dinesh, I am a passionate AI enthusiast with a strong foundation in Artificial Intelligence and Machine Learning, dedicated to creating innovative solutions that push the boundaries of technology. My academic and professional journey has equipped me with expertise in data science, machine learning, and AI engineering, with hands-on experience in projects like news classification, phishing website detection, and credit card fraud analysis. Proficient in Python, Java, SQL, and JavaScript, I leverage tools such as TensorFlow, Pandas, and Power BI to transform data into actionable insights. I am committed to contributing to the development of intelligent systems that drive innovation, enhance efficiency, and make a meaningful impact across industries. Let's connect and explore opportunities to shape the future of technology together.
    imageUrl: "home/IMG_0155.jpg"
    imageWidth: 260
    imageHeight: 260
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:dineshkumardavanam02@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/drdk02/"
    - name: "github"
      url: "https://github.com/dineshkumardavanam"
    - name: "cv"
      url: "https://docs.google.com/document/d/1_f8Hxcz6JfqmzQVRkwiD01OtJi1S6VgTUFyd8FA2GGU/edit?usp=sharing"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
